test_3 30Вызов функции 'test_3' с аргументами: (), {}
Функция 'test_3' вызвала исключение: TypeError
Вызов функции 'test_3' с аргументами: (), {}
Функция 'test_3' вызвала исключение: TypeError
